#ifndef EH_FLAGS_H
#define EH_FLAGS_H

#define EH_PARTICLE_STATIC 1
#define EH_PARTICLE_STATICMOVE 2
#define EH_PARTICLE_LEFT 4
#define EH_PARTICLE_UP 256
#define EH_PARTICLE_DOWN 512
#define EH_PARTICLE_CYLINDER 32
#define EH_PARTICLE_NOFORCE 128

#define DISTANCE_EPS_SQ 1e-4
#define GRADIENT_TENSOR_EPS 1e-3
#define LAPLACIAN_TENSOR_EPS 1e-1

#define EH_PARTICLE_BAND_FLAG 262144
#define EH_PARTICLE_PRESSURECLAMP 1024

#endif
