#ifndef EH_FLAGS_H
#define EH_FLAGS_H

#define EH_PARTICLE_STATIC 1
#define EH_PARTICLE_STATICMOVE 2
#define EH_PARTICLE_NOFORCE 4
#define EH_PARTICLE_PLOT 8
#define EH_PARTICLE_PRESSURECLAMP 16

#define EH_PARTICLE_WALL 32
#define EH_PARTICLE_FLUID 64

#define DISTANCE_EPS_SQ 1e-4
#define GRADIENT_TENSOR_EPS 1e-3
#define LAPLACIAN_TENSOR_EPS 1e-1


#endif
